[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "llama-optimus"
version = "0.2.0"
description = "llama-optimus is a lightweight Python tool to automatically optimize llama.cpp performance flags for maximum tg & pp token/s throughput. Powered by Bayesian optimization with Optuna"
authors = [
  { name = "Bruno Arsioli" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"
dependencies = [
  "optuna>=3.0",
  "pandas"
]
keywords = ["llama.cpp", "optimization", "AI", "Optuna", "performance"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/BrunoArsioli/llama-optimus"
Repository = "https://github.com/BrunoArsioli/llama-optimus"
"Bug Tracker" = "https://github.com/BrunoArsioli/llama-optimus/issues"

[project.scripts]
llama-optimus = "llama_optimus.cli:main"
llama-optimus-gui = "llama_optimus.gui:main"

[tool.setuptools]
package-dir = {"" = "src"}




